language: go
go:
  - tip
notifications:
  email:
    recipients:
      - dave@dhrapson.com
before_install:
  - rvm install 2.1.7
script:
  - go test -v ./...
  - ls -l
  - pwd
  - src/github.com/dhrapson/resembleio/run_specs.sh
